name: Staging Branch CI

on:
  push:
    branches: [ staging ]

jobs:
  integration-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'

    - name: Install dependencies
      run: npm ci

    - name: Run unit tests
      run: npm run test:unit

    - name: Run integration tests
      run: npm run test:integration

    - name: Build application
      run: npm run build

    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: build-files
        path: dist/

  deploy-staging:
    needs: integration-test
    runs-on: ubuntu-latest
    
    steps:
    - name: Download build artifacts
      uses: actions/download-artifact@v4
      with:
        name: build-files
        path: dist/

    - name: Deploy to staging environment
      run: |
        echo "Deploying to staging server..."
        # Thêm logic deploy staging ở đây
        echo "Staging deployment completed!"

  auto-merge-to-production:
    needs: [integration-test, deploy-staging]
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
        token: ${{ secrets.GITHUB_TOKEN }}

    - name: Merge to production
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git checkout production
        git merge staging --no-ff -m "Auto-merge staging to production"
        git push origin production
